In [ ]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [ ]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [ ]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.433995       NaN       NaN
1  0.267462       NaN       NaN
2 -0.556242       NaN  0.178580
3  0.808382       NaN -0.764808
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
df.dropna()

0         1         2
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
df.dropna(thresh=2)

0         1         2
2 -0.556242       NaN  0.178580
3  0.808382       NaN -0.764808
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
df.fillna(0)

0         1         2
0  0.433995  0.000000  0.000000
1  0.267462  0.000000  0.000000
2 -0.556242  0.000000  0.178580
3  0.808382  0.000000 -0.764808
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.433995  0.500000  0.000000
1  0.267462  0.500000  0.000000
2 -0.556242  0.500000  0.178580
3  0.808382  0.500000 -0.764808
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  0.433995  0.000000  0.000000
1  0.267462  0.000000  0.000000
2 -0.556242  0.000000  0.178580
3  0.808382  0.000000 -0.764808
4  0.316958 -1.611566 -0.900395
5  0.666147  0.469969  0.486021
6  1.448033 -0.953801 -0.414354

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0 -0.885062 -0.144022 -1.161074
1  0.674628 -1.763583  0.466262
2 -0.514522       NaN -1.519534
3 -0.756187       NaN -0.276320
4 -1.697925       NaN       NaN
5  0.490138       NaN       NaN

In [ ]:
df.fillna(method='ffill')

0         1         2
0 -0.885062 -0.144022 -1.161074
1  0.674628 -1.763583  0.466262
2 -0.514522 -1.763583 -1.519534
3 -0.756187 -1.763583 -0.276320
4 -1.697925 -1.763583 -0.276320
5  0.490138 -1.763583 -0.276320

In [ ]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.885062 -0.144022 -1.161074
1  0.674628 -1.763583  0.466262
2 -0.514522 -1.763583 -1.519534
3 -0.756187 -1.763583 -0.276320
4 -1.697925       NaN -0.276320
5  0.490138       NaN -0.276320

In [ ]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [ ]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [ ]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [ ]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [ ]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'],
 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [ ]:
data.index = data.index.map(transform)
data


one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [ ]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'},
 columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

Discretization and Binning

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
cats.codes


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [ ]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [ ]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [ ]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [ ]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
group_names

['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [ ]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
data = np.random.rand(20)
data

array([0.73297528, 0.16939418, 0.60081199, 0.90509887, 0.27733471,
       0.88548884, 0.49402637, 0.40969711, 0.96016154, 0.88295617,
       0.25178118, 0.71119359, 0.45265134, 0.26959091, 0.55207573,
       0.04679596, 0.86651646, 0.60601233, 0.34617792, 0.93458575])

In [ ]:
pd.cut(data, 4, precision=2)


[(0.73, 0.96], (0.046, 0.28], (0.5, 0.73], (0.73, 0.96], (0.28, 0.5], ..., (0.046, 0.28], (0.73, 0.96], (0.5, 0.73], (0.28, 0.5], (0.73, 0.96]]
Length: 20
Categories (4, interval[float64]): [(0.046, 0.28] < (0.28, 0.5] < (0.5, 0.73] < (0.73, 0.96]]

In [ ]:
data = np.random.randn(1000)
data

array([-1.43987356e+00,  6.38518744e-01,  1.19986557e-01,  1.63875867e-01,
        1.17314158e-01,  2.24662932e-01, -1.78286113e+00, -2.98412051e-01,
        1.12433670e+00,  2.54272188e-01,  1.54258234e+00, -8.29383144e-01,
       -1.03520947e+00, -1.55387871e-02,  6.86575004e-01, -1.00451425e+00,
        5.64375896e-01,  1.66167264e+00,  7.84153898e-02,  1.34509982e+00,
        1.15493507e+00, -1.64114028e+00, -2.87424640e-01,  1.30054978e+00,
        2.93370424e+00,  1.02701078e+00,  1.32438216e+00,  1.24903687e-01,
        2.75222285e-01, -9.29986418e-01, -9.67917456e-01, -1.08090814e+00,
       -1.30296152e+00,  1.55584310e-01, -2.11014823e+00,  8.53170893e-01,
       -4.41725908e-01,  1.27236270e+00,  3.45322190e-01, -1.19383189e+00,
       -4.11382942e-01,  4.10151080e-01,  1.04390847e+00,  3.48408998e-01,
       -2.20676326e-01,  3.55507639e-01, -1.03383609e+00,  1.46201023e+00,
        4.60720914e-02, -1.15832930e+00, -2.63570918e-01,  4.73220066e-01,
       -6.43489494e-01, -

In [ ]:
cats = pd.qcut(data, 4)
cats

[(-2.884, -0.655], (0.0368, 0.645], (0.0368, 0.645], (0.0368, 0.645], (0.0368, 0.645], ..., (0.0368, 0.645], (0.0368, 0.645], (-0.655, 0.0368], (0.0368, 0.645], (0.0368, 0.645]]
Length: 1000
Categories (4, interval[float64]): [(-2.884, -0.655] < (-0.655, 0.0368] < (0.0368, 0.645] <
                                    (0.645, 3.34]]

In [ ]:
pd.value_counts(cats)

(0.645, 3.34]       250
(0.0368, 0.645]     250
(-0.655, 0.0368]    250
(-2.884, -0.655]    250
dtype: int64

In [ ]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-2.884, -1.308], (0.0368, 1.308], (0.0368, 1.308], (0.0368, 1.308], (0.0368, 1.308], ..., (0.0368, 1.308], (0.0368, 1.308], (-1.308, 0.0368], (0.0368, 1.308], (0.0368, 1.308]]
Length: 1000
Categories (4, interval[float64]): [(-2.884, -1.308] < (-1.308, 0.0368] < (0.0368, 1.308] <
                                    (1.308, 3.34]]

Detecting and Filtering Outliers

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.003496    -0.024812     0.013831     0.017754
std       1.020637     0.964646     1.001991     1.039345
min      -3.319632    -2.746873    -2.937585    -3.236989
25%      -0.684950    -0.692293    -0.658941    -0.696265
50%       0.025699    -0.034771     0.028350     0.026460
75%       0.680086     0.602843     0.673422     0.702358
max       2.792050     3.240992     2.854936     3.187548

In [ ]:
col = data[2]
col

0     -0.500468
1     -2.418381
2     -1.125190
3      0.494669
4      0.383966
         ...   
995   -0.254010
996    0.330611
997   -0.566959
998    0.292194
999   -0.196394
Name: 2, Length: 1000, dtype: float64

In [ ]:
col[np.abs(col) > 3]

Series([], Name: 2, dtype: float64)

In [ ]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
27  -3.032431  0.982363  0.420821 -0.725170
79  -3.319632 -0.696949 -1.471452  0.982392
163 -0.604932  3.040109 -1.583842  0.071007
428  0.029215  3.240992  0.927275  0.259363
506 -0.191844  0.058206 -0.522289 -3.236989
557 -0.466685 -0.689802 -0.928583  3.187548
668  0.186732  0.591386 -0.503375 -3.063693
677 -3.106264 -1.079553 -0.197498 -0.839421
848 -3.137855  0.307895  0.288383  0.566518
905 -3.282227  0.542434 -0.207736  0.084830
918 -3.299936  2.176485 -0.621862 -1.265093
978  0.909792  0.385587 -0.580945 -3.072488

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002317    -0.025093     0.013831     0.017940
std       1.017018     0.963733     1.001991     1.037672
min      -3.000000    -2.746873    -2.937585    -3.000000
25%      -0.684950    -0.692293    -0.658941    -0.696265
50%       0.025699    -0.034771     0.028350     0.026460
75%       0.680086     0.602843     0.673422     0.702358
max       2.792050     3.000000     2.854936     3.000000

In [ ]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0  1.0 -1.0 -1.0
2  1.0 -1.0 -1.0 -1.0
3  1.0 -1.0  1.0  1.0
4  1.0  1.0  1.0 -1.0

In [ ]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
sampler = np.random.permutation(5)
sampler

array([4, 0, 2, 3, 1])

In [ ]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [ ]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19

In [ ]:
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [ ]:
draws = choices.sample(n=10, replace=True)
draws

1    7
3    6
2   -1
1    7
3    6
0    5
1    7
2   -1
4    4
2   -1
dtype: int64

Computing Indicator/Dummy Variables

In [ ]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [ ]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
mnames = ['movie_id', 'title', 'genres']
mnames

['movie_id', 'title', 'genres']

In [ ]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_tables('/content/movie.dat', sep='::', header=None, names=mnames)
movies[:10]


AttributeError: ignored