In [ ]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

In [ ]:
list1=[]
list1


[]

In [ ]:
type(list1)

list

In [ ]:
list2=list(range(5))
list2

[0, 1, 2, 3, 4]

In [ ]:
list3=list(str(c)for c in list2 )
list3


['0', '1', '2', '3', '4']

In [ ]:
list4=[1,10,2,'Amit','c',True]
list4

[1, 10, 2, 'Amit', 'c', True]

In [ ]:
type(list4)
list4

[1, 10, 2, 'Amit', 'c', True]

In [ ]:
type(list4)

list

In [ ]:
[type(item)for item in list4]

[int, int, int, str, str, bool]

In [ ]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
#Automatic Conversion of values
np.array([10.1,2,3,4])

array([10.1,  2. ,  3. ,  4. ])

In [ ]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
#0 to 2 create 4 elements 0.0,0.5,1.0,1.5
#creation of an array of evenly spaced values for the given range
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,4))

array([[0.54619712, 0.44179984, 0.94773772, 0.48073488],
       [0.27604243, 0.0982058 , 0.4201837 , 0.79327545],
       [0.50253166, 0.6239651 , 0.48954873, 0.14217717]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.4390449 ,  1.4050367 , -1.52428013],
       [-1.90908082,  0.86840782, -1.90106816],
       [-0.42326234,  0.46213544,  1.96451359]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[0, 8, 9],
       [5, 6, 0],
       [7, 3, 3]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
import numpy as np
np.random.seed(40)
x1=np.random.randint(10,size=6)
x1

array([6, 7, 5, 8, 8, 2])

In [ ]:
import numpy as np
np.random.seed(100)
x2=np.random.randint(200,size=(2,4,2,2,3))
x2

array([[[[[  8,  24,  67],
          [103,  87,  79]],

         [[176, 138,  94],
          [180,  98,  53]]],


        [[[ 66,  14,  34],
          [ 24, 143, 107]],

         [[ 60,  58, 144],
          [137,  93,  86]]],


        [[[130, 155, 108],
          [132, 159, 129]],

         [[141, 100,   4],
          [ 91, 187,  67]]],


        [[[135,  49, 175],
          [193,  61,  14]],

         [[183, 199,  80],
          [  2, 121, 105]]]],



       [[[[147,  63, 181],
          [ 27,  56, 113]],

         [[158, 176,  47],
          [167, 109,  38]]],


        [[[172,  18, 192],
          [184, 162, 181]],

         [[ 17,  72,  13],
          [106,  30,  17]]],


        [[[ 53,  68, 178],
          [ 91, 181,  78]],

         [[  0,  13, 185],
          [106, 131,  70]]],


        [[[131, 138, 188],
          [131, 105, 176]],

         [[180,  43,  36],
          [  5,  71,  38]]]]])

In [ ]:
x2.shape

(2, 4, 2, 2, 3)

In [ ]:
x2.ndim

5

In [ ]:
x2.size

96

In [ ]:
x2.nbytes

768

In [ ]:
x2.itemsize

8